// <auto-generated />
using System;
using JobLess.Client.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace JobLess.Client.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260613180000_DodatoPrijaveNaOglase")]
    partial class DodatoPrijaveNaOglase
    {
    }
}
